//Code generated by Codegen

import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://testautomationpractice.blogspot.com/');
  await page.locator('#PageList2').getByRole('link', { name: 'Home' }).click();
  await expect(page.getByRole('textbox', { name: 'Enter Name' })).toBeVisible();
  await page.getByRole('heading', { name: 'Automation Testing Practice' }).click();
  await expect(page.locator('h1')).toContainText('Automation Testing Practice');
  await expect(page.getByRole('textbox', { name: 'Enter Name' })).toHaveValue('Vinod');
});

//Multiple windows handling by using codegen
test('test2', async ({ page }) => {
  await page.goto('https://demo.automationtesting.in/Windows.html');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'click' }).click();
  const page1 = await page1Promise;
  await page1.getByRole('link', { name: 'Downloads' }).click();
  await expect(page1.locator('#bindings')).toContainText('Selenium Clients and WebDriver Language Bindings');
  await page.getByRole('link', { name: 'Register' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
});


test('Handling Multiple windows' ,async ({page}) =>{

  await page.goto('https://demo.automationtesting.in/Windows.html');
  const page1 = page.waitForEvent('popup')
  await page.getByRole('button', { name: 'click' }).click();
  const newPage = await page1
  await newPage.getByRole('link', { name: 'Downloads' }).click();
  await expect(newPage.locator('#bindings')).toContainText('Selenium Clients and WebDriver Language Bindings');
  await page.bringToFront()
  await page.getByRole('link', { name: 'Register' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();

});

test('To Handle Multiple Separate Window' , async ({page}) =>{
  await page.goto("https://demo.automationtesting.in/Windows.html")
  await expect(page).toHaveTitle(/Frames & windows/);
  await page.getByRole('link' , {name : 'Home'}).click();
  await page.goBack();
  await page.getByRole('link' , {name : 'Register'}).click();
  await page.goBack();
  await page.getByRole('link' , {name : 'Open New Seperate Windows'}).click();
  const page2 = page.waitForEvent("popup");
  await page.getByRole('button', {name : 'click'}).click();
  const newPage = await page2 
  await expect(newPage.getByText("Selenium automates browsers. That's it!", {exact : true})).toBeVisible();
  await page.bringToFront()
  const switchTo =  page.getByRole('link' ,{name : 'SwitchTo'})
  await switchTo.hover()
  const alerts =  page.getByRole('link' ,{name : 'Alerts'})
  await alerts.click();
});

test('To handle alerts' , async ({page}) => {

  page.goto("https://demoqa.com/alerts");

  const text = "Testing"

  page.on('dialog' , (dialog)=>{
    console.log(dialog.message())
    dialog.accept(text)
  })

  await page.locator("#alertButton").click()
  await page.locator("#confirmButton").click()
  
  await expect(page.locator("#confirmResult")).toHaveText("You selected Ok")

  await page.locator("#promtButton").click()
  await expect(page.locator("#promptResult")).toHaveText(`You entered ${text}`)

})
